### ISSUE TITLE
Cell / Column misalignment issue when tables created in Athena

### ISSUE THREAD

**Issue by nickdegiacomo** [MeltanoLabs/target-athena#27]
I have been trying to run a tap-shopify to target-athena pipeline. However, when checking created tables in Athena, some cells are misaligned. 

The same issue happens in target-csv. The data is heavily nested and includes arrays of JSON. e.g., If a customer purchases 1 item vs. five items, then line_items (and other columns) will grow to fit information on each.

**Comment by visch** [comment]
Thanks @nickdegiacomo :D

**Comment by aaronsteers** [comment]
Note the related bug in target-csv has been resolved, and is available for replicating here if/when someone needs CSV support prioritized. (Prior resolution was to make jsonl the default.)

https://github.com/MeltanoLabs/target-csv
