### ISSUE TITLE
Hyphen is not allowed in Athena table name

### ISSUE THREAD

**Issue by yummydum** [MeltanoLabs/target-athena#33]
When the input stream is DB, Meltano's naming convention for entity and attributes commonly has the form `<DB name>-<table name>.<column name>`, which includes a hyphen. The current implementation tries to create an Athena table with this naming convention, but hyphens are not allowed in the Athena table.

https://docs.aws.amazon.com/athena/latest/ug/glue-best-practices.html#schema-names
> The only acceptable characters for database names, table names, and column names are lowercase letters, numbers, and the underscore character.

A quick fix may be converting hyphens to underscores when creating the DDL. What do you think?

**Comment by yummydum** [comment]
Probably, changing this line
https://github.com/MeltanoLabs/target-athena/blob/ea2698028a68a5ecbbf7dc261deec5f472100356/target_athena/athena.py#L203

to
```
database=database.replace("-","_")
```

would suffice

**Comment by pnadolny13** [comment]
Closed by: https://github.com/MeltanoLabs/target-athena/pull/42
